[workspace]
members = [
    "local",
]
resolver = "2"

[workspace.dependencies]
tokio = "1.43.0"
clap = "4.5.18"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
thiserror = "2.0.12"
axum = "0.8.1"
serde = "1.0.219"
base64 = "0.22.1"
rocksdb = "0.22.0"
rand = "0.8.5"
bincode = "1.3.3"
dashmap = "5.5.3"
tokio-stream = "0.1.15"
futures = "0.3.30"

[profile.bench]
# Because we enable overflow checks in "release," we should benchmark with them.
overflow-checks = true

[profile.dev]
# Although overflow checks are enabled by default in "dev", we explicitly
# enable them here for clarity.
overflow-checks = true

[profile.release]
# To guard against unexpected behavior in production, we enable overflow checks in
# "release" although they incur some performance penalty.
overflow-checks = true

[profile.release-with-debug]
inherits = "release"
# Setting debug to true instructs cargo to include debug symbols in the release
# binary (not to disable optimizations).
debug = true

[profile.test]
# Although overflow checks are enabled by default in "test", we explicitly
# enable them here for clarity.
overflow-checks = true