openapi: 3.0.0
info:
  title: Exoware API
  version: 0.0.1
  description: API for Exoware simulator components (store and stream).
  contact:
    name: Exoware Team
    url: "https://github.com/exoware/exoware"
tags:
  - name: store
    description: "Key-value store operations"
  - name: stream
    description: "Stream operations"
servers:
  - url: http://localhost:8080
    description: Local simulator server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []

paths:
  /store/{key}:
    parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
        description: The key for the store operation.
    get:
      summary: Get a value
      operationId: getValue
      tags:
        - store
      description: Retrieves a value from the store by its key. Respects eventual consistency.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    format: byte
                    description: The base64-encoded value.
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      summary: Set a value
      operationId: setValue
      tags:
        - store
      description: Sets a key-value pair in the store. Enforces size limits and eventual consistency.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '413':
          description: Payload Too Large
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error

  /store:
    get:
      summary: Query for key-value pairs
      operationId: queryValues
      tags:
        - store
      description: Queries for a range of key-value pairs, respecting eventual consistency.
      parameters:
        - name: start
          in: query
          required: false
          schema:
            type: string
          description: The key to start the query from (inclusive).
        - name: end
          in: query
          required: false
          schema:
            type: string
          description: The key to end the query at (exclusive).
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: The maximum number of results to return.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                          format: byte
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /stream/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
        description: The name of the stream.
    post:
      summary: Publish to a stream
      operationId: publishToStream
      tags:
        - stream
      description: Publishes a message to a stream.
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    get:
      summary: Subscribe to a stream
      operationId: subscribeToStream
      tags:
        - stream
      description: Subscribes to a stream via WebSocket.
      responses:
        '101':
          description: Switching Protocols
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error