openapi: 3.0.0
info:
  title: Exoware API
  version: 0.0.1
  description: API for Exoware simulator components (store and stream).
  contact:
    name: Exoware Team
    url: "https://github.com/exoware/exoware"
tags:
  - name: store
    description: "Key-value store operations"
  - name: stream
    description: "Stream operations"
servers:
  - url: http://localhost:8080
    description: Local simulator server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Bearer token authentication.

security:
  - bearerAuth: []

paths:
  /store/{key}:
    parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
        description: The key for the store operation.
    get:
      summary: Get a value
      operationId: getValue
      tags:
        - store
      description: |
        Retrieves a value from the store by its key.

        **Consistency Note:** This store is eventually consistent. A key set or updated via a `POST` request may take up to 60 seconds to be available via this endpoint.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    format: byte
                    description: The base64-encoded value.
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      summary: Set a value
      operationId: setValue
      tags:
        - store
      description: Sets a key-value pair in the store.
      x-invariants:
        - type: eventual-consistency
          description: "A key written by this operation may take up to 60 seconds to be readable from the GET /store/{key} operation."
          latency_seconds: 60
        - type: rate-limit
          description: "This operation can be called at most once per second for each key."
          limit: 1
          period_seconds: 1
          scope: key
        - type: max-key-size
          description: "The maximum size of the key is 512 bytes."
          limit_bytes: 512
        - type: max-value-size
          description: "The maximum size of the value is 20MB (20971520 bytes)."
          limit_bytes: 20971520
      requestBody:
        description: The raw binary value to store.
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '413':
          description: Payload Too Large
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error

  /store:
    get:
      summary: Query for key-value pairs
      operationId: queryValues
      tags:
        - store
      description: Queries for a range of key-value pairs, respecting eventual consistency.
      parameters:
        - name: start
          in: query
          required: false
          schema:
            type: string
          description: The key to start the query from (inclusive).
        - name: end
          in: query
          required: false
          schema:
            type: string
          description: The key to end the query at (exclusive).
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: The maximum number of results to return.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                          format: byte
                          description: The base64-encoded value.
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /stream/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
        description: The name of the stream.
    post:
      summary: Publish to a stream
      operationId: publishToStream
      tags:
        - stream
      description: Publishes a message to a stream.
      requestBody:
        description: The raw binary message to publish.
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    get:
      summary: Subscribe to a stream
      operationId: subscribeToStream
      tags:
        - stream
      description: |
        Subscribes to a stream via WebSocket.

        **Authentication:** This endpoint supports authentication via the standard `Authorization: Bearer <token>` header, or by providing the token in the `auth_token` query parameter. If the server is configured with `--allow-public-access`, this endpoint can be accessed without authentication.
      parameters:
        - name: auth_token
          in: query
          required: false
          schema:
            type: string
          description: "Authentication token, can be used as an alternative to the `Authorization` header."
      responses:
        '101':
          description: Switching Protocols
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error