name: Publish

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  All:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run setup
      uses: ./.github/actions/setup
    - name: Publish simulator
      run: cargo publish --manifest-path simulator/Cargo.toml
      continue-on-error: true
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Publish sdk
      run: cargo publish --manifest-path sdk/Cargo.toml
      continue-on-error: true
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}