name: Publish

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  All:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run setup
      uses: ./.github/actions/setup
    - name: Publish simulator
      run: cargo publish --manifest-path simulator/Cargo.toml
      continue-on-error: true
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Publish sdk
      run: cargo publish --manifest-path sdk/Cargo.toml
      continue-on-error: true
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: Publish sdk-ts
      run: |
        cd sdk-ts
        npm install
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}